package igu.productos;

import Eventos.Eventos;
import entidades.Producto;
import implementacion.ImplProducto;
import interfaceDao.IProductosDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB REDES
 */
public class ProductoJDialog extends javax.swing.JDialog {

    Eventos event = new Eventos();
    IProductosDao metodos = new ImplProducto();
    DefaultTableModel modelo;

    public ProductoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //ListarDatos();
        ReporteData();
        setTitle("Gestion de Productos");
    }

    public void ListarDatos() {
        ArrayList<Producto> ListarPro = metodos.reporteProductos();
        modelo = (DefaultTableModel) jTableProductos.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < ListarPro.size(); i++) {
            ob[0] = ListarPro.get(i).getId();
            ob[1] = ListarPro.get(i).getNombre();
            ob[2] = ListarPro.get(i).getMarca();
            ob[3] = ListarPro.get(i).getModelo();
            ob[4] = ListarPro.get(i).getTalla();
            ob[5] = ListarPro.get(i).getPrecio();
            ob[6] = ListarPro.get(i).getStock();
            modelo.addRow(ob);
        }
        jTableProductos.setModel(modelo);
    }

    public void ReporteData() {
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Talla");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        Object[] fila = new Object[7];
        for (Producto pro : metodos.reporteProductos()) {      
            fila[0] = pro.getId();
            fila[1] = pro.getNombre();
            fila[2] = pro.getMarca();
            fila[3] = pro.getModelo();
            fila[4] = pro.getTalla();
            fila[5] = pro.getPrecio();
            fila[6] = pro.getStock();
            modelo.addRow(fila);
        }
        jTableProductos.setModel(modelo);
    }

    public void limpiarTabla(JTable table) {
        modelo = (DefaultTableModel) table.getModel();
        int fila = table.getRowCount();
        for (int i = 0; i < fila; i++) {
            modelo.removeRow(0);
        }
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        p_nombre = new javax.swing.JTextField();
        p_marca = new javax.swing.JTextField();
        p_modelo = new javax.swing.JTextField();
        p_talla = new javax.swing.JTextField();
        p_precio = new javax.swing.JTextField();
        jButtonGrabar = new javax.swing.JButton();
        p_stock = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        p_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 116, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Talla:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 155, -1, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 195, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, -1, -1));

        p_nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        p_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(p_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 36, 150, -1));

        p_marca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel1.add(p_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 75, 150, -1));

        p_modelo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        p_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_modeloActionPerformed(evt);
            }
        });
        jPanel1.add(p_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 112, 150, -1));

        p_talla.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel1.add(p_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, -1));

        p_precio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        p_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p_precioKeyTyped(evt);
            }
        });
        jPanel1.add(p_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 150, -1));

        jButtonGrabar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonGrabar.setText("Grabar");
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 270, 90, 50));

        p_stock.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        p_stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p_stockKeyTyped(evt);
            }
        });
        jPanel1.add(p_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, -1));

        jButtonEliminar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 100, 50));

        btn_Actualizar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 50));

        p_id.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 0, 0));

        jButton1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButton1.setText("NUEVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 20));

        jPanelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 300, 340));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jTableProductos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripcion", "Marca", "Modelo", "Talla", "Precio", "Stock"
            }
        ));
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTableProductos.getColumnModel().getColumn(5).setPreferredWidth(35);
        }

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 640, 340));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel5.setText("TABLA PRODUCTOS");
        jPanelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 14, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_nombreActionPerformed

    private void p_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_modeloActionPerformed

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed

        Producto pro = new Producto();

        if (!"".equals(p_nombre.getText()) || !"".equals(p_marca.getText()) || !"".equals(p_modelo.getText()) || !"".equals(p_talla.getText()) || !"".equals(p_precio.getText()) || !"".equals(p_stock.getText())) {
            pro.setNombre(p_nombre.getText());
            pro.setMarca(p_marca.getText());
            pro.setModelo(p_modelo.getText());
            pro.setTalla(p_talla.getText());
            pro.setPrecio(Double.parseDouble(p_precio.getText()));
            pro.setStock(Integer.parseInt(p_stock.getText()));
            metodos.registrarProducto(pro);
            p_nombre.setText("");
            p_marca.setText("");
            p_modelo.setText("");
            p_talla.setText("");
            p_precio.setText("");
            p_stock.setText("");

            JOptionPane.showMessageDialog(
                    null,
                    "Se registro con Exito",
                    "Registro",
                    JOptionPane.INFORMATION_MESSAGE);
            LimpiarTable();
            //ListarDatos();
            ReporteData();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Completa el registro para\n" + "guardar un producto",
                    "Error/Advertencia",
                    JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonGrabarActionPerformed

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        int row = jTableProductos.getSelectedRow();
        String id = jTableProductos.getValueAt(row, 0).toString();
        String nombre = jTableProductos.getValueAt(row, 1).toString();
        String marca = jTableProductos.getValueAt(row, 2).toString();
        String modelo = jTableProductos.getValueAt(row, 3).toString();
        String talla = jTableProductos.getValueAt(row, 4).toString();
        String precio = jTableProductos.getValueAt(row, 5).toString();
        String stock = jTableProductos.getValueAt(row, 6).toString();
        p_id.setText(id);
        p_nombre.setText(nombre);
        p_marca.setText(marca);
        p_modelo.setText(modelo);
        p_talla.setText(talla);
        p_precio.setText(precio);
        p_stock.setText(stock);
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if (!"".equals(p_id.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?");
            if (pregunta == 0) {
                String id = p_id.getText();
                metodos.eliminarRegistroProducto(id);
                LimpiarTable();
                p_id.setText("");
                p_nombre.setText("");
                p_marca.setText("");
                p_modelo.setText("");
                p_talla.setText("");
                p_precio.setText("");
                p_stock.setText("");
                //ListarDatos();
                ReporteData();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        //String nombre = p_nombre.getText();
        Producto pro = new Producto();
        if (!"".equals(p_nombre.getText())) {
            JOptionPane.showMessageDialog(null, "Se actualizo con exito");
            pro.setId(p_id.getText());
            pro.setNombre(p_nombre.getText());
            pro.setMarca(p_marca.getText());
            pro.setModelo(p_modelo.getText());
            pro.setTalla(p_talla.getText());
            pro.setPrecio(Double.parseDouble(p_precio.getText()));
            pro.setStock(Integer.parseInt(p_stock.getText()));
            metodos.actualizarRegistroProducto(pro);
            LimpiarTable();
            p_id.setText("");
            p_nombre.setText("");
            p_marca.setText("");
            p_modelo.setText("");
            p_talla.setText("");
            p_precio.setText("");
            p_stock.setText("");
            //ListarDatos();
            ReporteData();
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
        }
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void p_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_precioKeyTyped
        event.numberDecimalKeyPress(evt, p_precio);
    }//GEN-LAST:event_p_precioKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        p_id.setText("");
        p_nombre.setText("");
        p_marca.setText("");
        p_modelo.setText("");
        p_talla.setText("");
        p_precio.setText("");
        p_stock.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void p_stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_stockKeyTyped
        event.numberKeyPress(evt);
    }//GEN-LAST:event_p_stockKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoJDialog dialog = new ProductoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField p_id;
    private javax.swing.JTextField p_marca;
    private javax.swing.JTextField p_modelo;
    private javax.swing.JTextField p_nombre;
    private javax.swing.JTextField p_precio;
    private javax.swing.JTextField p_stock;
    private javax.swing.JTextField p_talla;
    // End of variables declaration//GEN-END:variables

}
