/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu.clientes;

import entidades.Persona;
import implementacion.ImplPersona;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB REDES
 */
public class ClientesJDialog extends javax.swing.JDialog {

    //MetodosSistema metodos= new MetodosSistema();
    ImplPersona metodos = new ImplPersona();
    DefaultTableModel modelo;
    ButtonGroup sexo = new ButtonGroup();

    public ClientesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListarDatos();
        setTitle("Gestion de Clientes");
        sexo.add(v_femenino);
        sexo.add(v_masculino);
    }

    public void limpiarTabla(JTable table) {
        modelo = (DefaultTableModel) table.getModel();
        int fila = table.getRowCount();
        for (int i = 0; i < fila; i++) {
            modelo.removeRow(0);
        }
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        v_nombre = new javax.swing.JTextField();
        v_paterno = new javax.swing.JTextField();
        v_materno = new javax.swing.JTextField();
        v_codigo = new javax.swing.JTextField();
        v_masculino = new javax.swing.JRadioButton();
        v_femenino = new javax.swing.JRadioButton();
        v_usuario = new javax.swing.JTextField();
        v_contrasenia = new javax.swing.JPasswordField();
        jButtonGrabar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        v_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 58, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ap.Paterno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ap. Materno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Codigo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, -1, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 247, -1, -1));

        v_nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        v_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(v_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 52, 150, -1));

        v_paterno.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel1.add(v_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 83, 150, -1));

        v_materno.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        v_materno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_maternoActionPerformed(evt);
            }
        });
        jPanel1.add(v_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 114, 150, -1));

        v_codigo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel1.add(v_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 145, 150, -1));

        buttonGroupSexo.add(v_masculino);
        v_masculino.setForeground(new java.awt.Color(255, 255, 255));
        v_masculino.setText("Masculino");
        jPanel1.add(v_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        buttonGroupSexo.add(v_femenino);
        v_femenino.setForeground(new java.awt.Color(255, 255, 255));
        v_femenino.setText("Femenino");
        jPanel1.add(v_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        v_usuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel1.add(v_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 210, 150, -1));

        v_contrasenia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel1.add(v_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 242, 150, -1));

        jButtonGrabar.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jButtonGrabar.setText("Grabar");
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 50));

        jButtonEliminar.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 100, 50));
        jPanel1.add(v_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 309, 353));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jTablePersonas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Paterno", "Materno", "DNI"
            }
        ));
        jTablePersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonas);
        if (jTablePersonas.getColumnModel().getColumnCount() > 0) {
            jTablePersonas.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 619, 348));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void v_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_nombreActionPerformed

    private void v_maternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_maternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_maternoActionPerformed

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed

        Persona dp = new Persona();
        dp.setNombre(v_nombre.getText());
        dp.setAp_paterno(v_paterno.getText());
        dp.setAp_materno(v_materno.getText());
        dp.setCodigo(v_codigo.getText());
        dp.setUsuario(v_usuario.getText());
        dp.setPassword(v_contrasenia.getText());

        if (v_femenino.isSelected() == true) {
            dp.setSexo("F");
        }
        if (v_masculino.isSelected() == true) {
            dp.setSexo("M");
        }

        if (!v_nombre.getText().equals("") || !v_paterno.getText().equals("") || !v_materno.getText().equals("") || !v_codigo.getText().equals("")) {
            metodos.registrarPersona(dp);
            v_id.setText("");
            v_nombre.setText("");
            v_paterno.setText("");
            v_materno.setText("");
            sexo.clearSelection();
            v_usuario.setText("");
            v_contrasenia.setText("");
            v_codigo.setText("");
            JOptionPane.showMessageDialog(
                    null,
                    "Se registro con Exito",
                    "Registro",
                    JOptionPane.INFORMATION_MESSAGE);
            LimpiarTable();
            ListarDatos();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "No se registro",
                    "Error/Advertencia",
                    JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonGrabarActionPerformed

    private void jTablePersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonasMouseClicked
        int row = jTablePersonas.getSelectedRow();
        String id = jTablePersonas.getValueAt(row, 0).toString();
        String nombre = jTablePersonas.getValueAt(row, 1).toString();
        String paterno = jTablePersonas.getValueAt(row, 2).toString();
        String materno = jTablePersonas.getValueAt(row, 3).toString();
        String codigo = jTablePersonas.getValueAt(row, 4).toString();

        System.out.println("Holasss" + nombre + paterno + materno);
        v_id.setText(id);
        v_nombre.setText(nombre);
        v_paterno.setText(paterno);
        v_materno.setText(materno);
        v_codigo.setText(codigo);
    }//GEN-LAST:event_jTablePersonasMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String id = v_id.getText();
        if (!"".equals(v_nombre.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?");
            if (pregunta == 0) {
                metodos.eliminarRegistroPersona(id);
                LimpiarTable();
                v_id.setText("");
                v_nombre.setText("");
                v_paterno.setText("");
                v_materno.setText("");
                v_usuario.setText("");
                sexo.clearSelection();
                v_contrasenia.setText("");
                v_codigo.setText("");
                ListarDatos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    public void ListarDatos() {
        ArrayList<Persona> Listarp = metodos.reportePersonas();
        modelo = (DefaultTableModel) jTablePersonas.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < Listarp.size(); i++) {
            ob[0] = Listarp.get(i).getId();
            ob[1] = Listarp.get(i).getNombre();
            ob[2] = Listarp.get(i).getAp_paterno();
            ob[3] = Listarp.get(i).getAp_materno();
            ob[4] = Listarp.get(i).getCodigo();
            modelo.addRow(ob);
        }
        jTablePersonas.setModel(modelo);
    }

    public void ReporteData() {
        /*
            String columnas[] = {"Nombres","Ap. Paterno","Ap. Materno","Codigo"};
            Object filas[][] = new Object[metodos.reportePersonas().size()][4];
                  
          
                  jTablePersonas= new JTable(filas, columnas);
                  JScrollPane tabla1= new JScrollPane(jTablePersonas);
          -*/

        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Paterno");
        modelo.addColumn("Materno");
        modelo.addColumn("Codigo");

        for (Persona pers : metodos.reportePersonas()) {
            Object[] fila = new Object[4];
            fila[0] = pers.getNombre();
            fila[1] = pers.getAp_paterno();
            fila[2] = pers.getAp_materno();
            fila[3] = pers.getCodigo();
            modelo.addRow(fila);
        }
        //jTablePersonas = new JTable();
        jTablePersonas.setModel(modelo);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientesJDialog dialog = new ClientesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonas;
    private javax.swing.JTextField v_codigo;
    private javax.swing.JPasswordField v_contrasenia;
    private javax.swing.JRadioButton v_femenino;
    private javax.swing.JTextField v_id;
    private javax.swing.JRadioButton v_masculino;
    private javax.swing.JTextField v_materno;
    private javax.swing.JTextField v_nombre;
    private javax.swing.JTextField v_paterno;
    private javax.swing.JTextField v_usuario;
    // End of variables declaration//GEN-END:variables
}
