/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu.clientes;

import entidades.Persona;
import implementacion.ImplPersona;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB REDES
 */
public class ClientesJDialog extends javax.swing.JDialog {

    //MetodosSistema metodos= new MetodosSistema();
    ImplPersona metodos = new ImplPersona();
    DefaultTableModel modelo;

    public ClientesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListarDatos();
//        ReporteData();
        setTitle("Gestion de Clientes");
    }

    public void limpiarTabla(JTable table) {
        modelo = (DefaultTableModel) table.getModel();
        int fila = table.getRowCount();
        for (int i = 0; i < fila; i++) {
            modelo.removeRow(0);
        }
    }
    
    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        v_nombre = new javax.swing.JTextField();
        v_paterno = new javax.swing.JTextField();
        v_materno = new javax.swing.JTextField();
        v_codigo = new javax.swing.JTextField();
        v_masculino = new javax.swing.JRadioButton();
        v_femenino = new javax.swing.JRadioButton();
        v_usuario = new javax.swing.JTextField();
        v_contrasenia = new javax.swing.JPasswordField();
        jButtonGrabar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Clientes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 55, -1, -1));

        jLabel2.setText("Ap.Paterno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 86, -1, -1));

        jLabel3.setText("Ap. Materno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 117, -1, -1));

        jLabel4.setText("Codigo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 148, -1, -1));

        jLabel5.setText("Sexo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 176, -1, -1));

        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 201, -1, -1));

        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 227, -1, -1));

        v_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(v_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 52, 126, -1));
        jPanel1.add(v_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 83, 126, -1));

        v_materno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_maternoActionPerformed(evt);
            }
        });
        jPanel1.add(v_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 114, 126, -1));
        jPanel1.add(v_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 145, 126, -1));

        buttonGroupSexo.add(v_masculino);
        v_masculino.setText("Masculino");
        jPanel1.add(v_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 176, -1, -1));

        buttonGroupSexo.add(v_femenino);
        v_femenino.setText("Femenino");
        jPanel1.add(v_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 176, -1, -1));
        jPanel1.add(v_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 201, 131, -1));
        jPanel1.add(v_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 227, 131, -1));

        jButtonGrabar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonGrabar.setText("Grabar");
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 298, 201, 37));

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Paterno", "Materno", "Codigo"
            }
        ));
        jTablePersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonas);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(Limpiar)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(665, Short.MAX_VALUE)))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Limpiar)
                .addGap(194, 194, 194))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void v_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_nombreActionPerformed

    private void v_maternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_maternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_maternoActionPerformed

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed

        Persona dp = new Persona();
        dp.setNombre(v_nombre.getText());
        dp.setAp_paterno(v_paterno.getText());
        dp.setAp_materno(v_materno.getText());
        dp.setCodigo(v_codigo.getText());
        dp.setUsuario(v_usuario.getText());
        dp.setPassword(v_contrasenia.getText());

        if (v_femenino.isSelected() == true) {
            dp.setSexo("F");
        }
        if (v_masculino.isSelected() == true) {
            dp.setSexo("M");
        }

        if (!v_nombre.getText().equals("") || !v_paterno.getText().equals("") || !v_materno.getText().equals("") || !v_codigo.getText().equals("")) {
            metodos.registrarPersona(dp);
            v_nombre.setText("");
            v_paterno.setText("");
            v_materno.setText("");
            v_usuario.setText("");
            v_contrasenia.setText("");
            v_codigo.setText("");
            JOptionPane.showMessageDialog(
                    null,
                    "Se registro con Exito",
                    "Registro",
                    JOptionPane.INFORMATION_MESSAGE);
            LimpiarTable();
            ListarDatos();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "No se registro",
                    "Error/Advertencia",
                    JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonGrabarActionPerformed

    private void jTablePersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonasMouseClicked
        int row = jTablePersonas.getSelectedRow();
        String nombre = jTablePersonas.getValueAt(row, 0).toString();
        String paterno = jTablePersonas.getValueAt(row, 1).toString();
        String materno = jTablePersonas.getValueAt(row, 2).toString();

        System.out.println("Holasss" + nombre + paterno + materno);
        v_nombre.setText(nombre);
    }//GEN-LAST:event_jTablePersonasMouseClicked

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        LimpiarTable();
        ListarDatos();
    }//GEN-LAST:event_LimpiarActionPerformed

    public void ListarDatos(){
        ArrayList<Persona> Listarp = metodos.reportePersonas();
        modelo = (DefaultTableModel) jTablePersonas.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < Listarp.size(); i++) {
            ob[0] = Listarp.get(i).getNombre();
            ob[1] = Listarp.get(i).getAp_paterno();
            ob[2] = Listarp.get(i).getAp_materno();
            ob[3] = Listarp.get(i).getCodigo();
            modelo.addRow(ob);
        }
        jTablePersonas.setModel(modelo);
    }
    
    public void ReporteData() {
        /*
            String columnas[] = {"Nombres","Ap. Paterno","Ap. Materno","Codigo"};
            Object filas[][] = new Object[metodos.reportePersonas().size()][4];
                  
          
                  jTablePersonas= new JTable(filas, columnas);
                  JScrollPane tabla1= new JScrollPane(jTablePersonas);
          -*/
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Paterno");
        modelo.addColumn("Materno");
        modelo.addColumn("Codigo");
        
        for (Persona pers : metodos.reportePersonas()) {
            Object[] fila = new Object[4];
            fila[0] = pers.getNombre();
            fila[1] = pers.getAp_paterno();
            fila[2] = pers.getAp_materno();
            fila[3] = pers.getCodigo();
            modelo.addRow(fila);
        }
        //jTablePersonas = new JTable();
        jTablePersonas.setModel(modelo);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientesJDialog dialog = new ClientesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonas;
    private javax.swing.JTextField v_codigo;
    private javax.swing.JPasswordField v_contrasenia;
    private javax.swing.JRadioButton v_femenino;
    private javax.swing.JRadioButton v_masculino;
    private javax.swing.JTextField v_materno;
    private javax.swing.JTextField v_nombre;
    private javax.swing.JTextField v_paterno;
    private javax.swing.JTextField v_usuario;
    // End of variables declaration//GEN-END:variables
}
